- name: install packages 
    package:
      name:
        - python3
        - python3-pip
        - python3-dev
        - python3-psutil
        - libffi-dev
        - libssl-dev
        - docker-compose
        - tmux
        - vim-nox